[package]
name = "kp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
copypasta = "0.10.0"
keepass = "0.6.1"
rpassword = "7.2.0"
